from enum import Enum


class Action(Enum):
    KILLED = "killed"
    RESSED = "resurrected"


class Team(Enum):
    RED = "red"
    BLUE = "blue"
    UNKNOWN = "unknown"


class Hero(Enum):
    ANA = "Ana"
    ASHE = "Ashe"
    BAPTISTE = "Baptiste"
    BASTION = "Bastion"
    BRIGITTE = "Brigitte"
    DOOMFIST = "Doomfist"
    DVA = "Dva"
    #DVA_MECH = "Dva_mech"
    ECHO = "Echo"
    GENJI = "Genji"
    HANZO = "Hanzo"
    JUNKERQUEEN = "Junkerqueen"
    JUNKRAT = "Junkrat"
    LUCIO = "Lucio"
    KIRIKO = "Kiriko"
    MCREE = "Mcree"
    MEI = "Mei"
    MERCY = "Mercy"
    MOIRA = "Moira"
    ORISA = "Orisa"
    PHARAH = "Pharah"
    REAPER = "Reaper"
    REINHARDT = "Reinhardt"
    ROADHOG = "Roadhog"
    SIGMA = "Sigma"
    SOLDIER = "Soldier"
    SOMBRA = "Sombra"
    SOJOURN = "Sojourn"
    SYMMETRA = "Symmetra"
    TORBJORN = "Torbjorn"
    TRACER = "Tracer"
    WIDOWMAKER = "Widowmaker"
    WINSTON = "Winston"
    WRECKINGBALL = "Wreckingball"
    ZARYA = "Zarya"
    ZENYATTA = "Zenyatta"


class Ability(Enum):
    CRITICAL_HIT = "Critical_hit"
    BOB = "Bob"
    HOOK = "Hook"
    TRAP = "Trap"
    CONCUSSION_MINE = "Concussion_mine"
    FIRE_STRIKE = "Fire_strike"
    CHARGE = "Charge"
    RAILGUN = "Railgun"
    OVERCLOCK = "Overclock"
    DYNAMITE = "Dynamite"
    WHIP_SHOT = "Whip_shot"
    JAVELIN = "Javelin"
    SOUNDWAVE = "Soundwave"
    PULSE_BOMB = "Pulse_bomb"
    MELEE = "Melee"
    GRENADE = "Grenade"
    ARTILLERY = "Artillery"
    TURRET = "Turret"
    MOLTEN_CORE = "Molten_core"
    PRIMAL_RAGE = "Primal_rage"

